-- V14__create_refresh_tokens.sql
-- [목적] JWT refresh token 무효화(logout/rotation)를 위한 서버측 저장 테이블.
--        token_hash = SHA-256(raw_refresh_token) 만 저장 — DB 유출 시 원본 토큰 노출 방지.
-- [이유] Stateless JWT만으로는 logout 즉시 무효화가 불가능. DB에 해시를 저장하면
--        rotation(갱신 시 삭제+신규) + logout(삭제)으로 즉시 무효화 가능.
-- [사이드 임팩트] 모든 토큰 갱신/로그아웃이 이 테이블에 의존. 대규모 트래픽 시 인덱스 조회 부하.
-- [수정 시 고려사항] 만료 토큰 정기 삭제 배치(@Scheduled) 추가 권장. Redis 전환 시 이 테이블 불필요.

CREATE TABLE refresh_tokens (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64)  NOT NULL UNIQUE,    -- SHA-256(raw token) hex 64자
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  refresh_tokens IS 'JWT refresh token SHA-256 해시 저장. logout/rotation 즉시 무효화 지원.';
COMMENT ON COLUMN refresh_tokens.token_hash IS 'SHA-256(raw_refresh_token) hex 소문자. 원본 토큰 미저장.';

CREATE INDEX idx_refresh_tokens_user    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);
