-- V1__create_users.sql
-- [목적] 사용자·인증·BM등급·알림설정 기본 테이블 생성 (db_schema.md 3.1, 통합기획서 5.1).
-- [이유] 회원가입/인증(Spring Security+JWT, OAuth)·티어·알림설정의 루트 엔티티.
-- [사이드 임팩트] portfolios·notifications·consent_logs·feedbacks가 users(id)를 FK로 참조(이후 버전).
-- [수정 시 고려사항] 적용 후 불변 — 컬럼 추가는 새 V{n} 파일로만(V7이 알림 빈도/필터 컬럼 추가).
--                  enum류는 VARCHAR+CHECK로 두고 @Enumerated(STRING)과 동기화.

CREATE TABLE users (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL UNIQUE,
    password_hash       VARCHAR(255),                 -- OAuth 전용 계정은 NULL 허용
    oauth_provider      VARCHAR(10)  CHECK (oauth_provider IN ('KAKAO','GOOGLE','NAVER')),
    oauth_id            VARCHAR(255),
    nickname            VARCHAR(50)  NOT NULL,
    phone_number_enc    BYTEA,                         -- 알림톡 사용 시에만 수집(선택), AES-256
    tier                VARCHAR(10)  NOT NULL DEFAULT 'FREE'
                                     CHECK (tier IN ('FREE','PRO','PREMIUM')),
    tier_expires_at     TIMESTAMPTZ,                   -- 구독 만료(Free는 NULL)
    notify_channel      VARCHAR(10)  NOT NULL DEFAULT 'KAKAO'
                                     CHECK (notify_channel IN ('KAKAO','TELEGRAM','EMAIL')),
    notify_enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    terms_agreed_at     TIMESTAMPTZ  NOT NULL,         -- 필수: 서비스 약관
    privacy_agreed_at   TIMESTAMPTZ  NOT NULL,         -- 필수: 개인정보 처리방침
    marketing_agreed_at TIMESTAMPTZ,                   -- 선택: 광고성(친구톡 등)
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,                   -- soft delete(삭제권 보장)
    CONSTRAINT uq_users_oauth UNIQUE (oauth_provider, oauth_id)
);

COMMENT ON COLUMN users.phone_number_enc IS 'AES-256-GCM 암호화(IV‖ct‖tag). PII — 평문 로깅 금지';

CREATE INDEX idx_users_tier ON users (tier) WHERE deleted_at IS NULL;
