-- V3__create_portfolios.sql
-- [목적] 보유 종목 — 매수가/수량 AES-256 암호화 컬럼 포함 (db_schema.md 3.3, 통합기획서 11.1).
-- [이유] 사용자별 보유 종목 CRUD + 공시→영향 사용자 역조회의 기준.
-- [사이드 임팩트] 알림 발송 시 stock_code 역조회로 영향 사용자 집합 산출(feature_structure 2장).
-- [수정 시 고려사항] 매수가/수량은 암호화 저장이라 DB 정렬·연산 불가 → 손익은 복호화 후 앱 계층.
--                  Free 3종목 제한은 애플리케이션단 검증. users·stocks 의존(V1·V2 이후).

CREATE TABLE portfolios (
    id                 BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    stock_code         VARCHAR(6) NOT NULL REFERENCES stocks (stock_code),
    avg_buy_price_enc  BYTEA,                          -- 매수가(선택), AES-256
    quantity_enc       BYTEA,                          -- 수량(선택), AES-256
    memo               VARCHAR(200),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_portfolio_user_stock UNIQUE (user_id, stock_code)
);

COMMENT ON COLUMN portfolios.avg_buy_price_enc IS 'AES-256-GCM 암호화 매수가. 평문 저장/로깅 금지(통합기획서 11.1)';
COMMENT ON COLUMN portfolios.quantity_enc     IS 'AES-256-GCM 암호화 보유 수량. 평문 저장/로깅 금지';

CREATE INDEX idx_portfolios_user  ON portfolios (user_id);
CREATE INDEX idx_portfolios_stock ON portfolios (stock_code);  -- 공시→영향 사용자 역조회
