-- V4__create_disclosures.sql
-- [목적] 공시 원문 — 접수번호(rcept_no) 멱등 키. Stage 1 룰 추출 결과 포함 (db_schema.md 3.4).
-- [이유] DART OpenAPI 1분 폴링 수집 결과의 적재처. 중복 발송 방어의 1차 멱등(rcept_no UNIQUE).
-- [사이드 임팩트] V5 analysis_results·V6 notifications가 disclosures(id) FK 참조.
-- [수정 시 고려사항] corp_name/report_nm/수치/날짜는 DART 원본 그대로(LLM 변형 금지, CLAUDE.md 4장).
--                  대용량 본문은 attachment_url(외부 스토리지) 참조. stocks 의존(V2 이후).

CREATE TABLE disclosures (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rcept_no         VARCHAR(14)  NOT NULL UNIQUE,     -- DART 접수번호(14자리) = 멱등 키
    corp_code        VARCHAR(8)   NOT NULL,            -- DART 고유번호
    stock_code       VARCHAR(6)   REFERENCES stocks (stock_code),  -- 비상장 등 NULL 허용
    corp_name        VARCHAR(100) NOT NULL,            -- DART 원본(LLM 변형 금지)
    report_nm        VARCHAR(255) NOT NULL,            -- 공시 제목(원본)
    rcept_dt         DATE         NOT NULL,            -- 접수일자
    disclosure_type  VARCHAR(50)  NOT NULL,            -- 공시 유형(80여 종, 룰 분류)
    content_text     TEXT,                             -- 본문 추출 텍스트(Stage 1)
    attachment_url   VARCHAR(500),                     -- 대용량 원문 첨부(S3 등) 참조
    collected_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON COLUMN disclosures.corp_name IS 'DART 원본 인용 — LLM 변형 금지, 룰 기반(Stage 1) 추출';

CREATE INDEX idx_disclosures_corp     ON disclosures (corp_code, rcept_dt DESC);
CREATE INDEX idx_disclosures_stock    ON disclosures (stock_code, rcept_dt DESC);
CREATE INDEX idx_disclosures_type     ON disclosures (disclosure_type);
CREATE INDEX idx_disclosures_rcept_dt ON disclosures (rcept_dt DESC);
