-- V6__create_notifications.sql
-- [목적] 알림 발송 이력 — (user, disclosure, channel) 멱등으로 중복 발송 차단 (db_schema.md 3.6).
-- [이유] 채널별 발송 결과 기록 + 재시도(exponential backoff) 상태머신. 발송 멱등의 2차 방어.
-- [사이드 임팩트] 발송 디스패처가 status(PENDING→SENT/FAILED/RETRYING) 전이로 운영.
-- [수정 시 고려사항] 접수번호 멱등(disclosures.rcept_no)과 이중 방어(CLAUDE.md 4장).
--                  users·disclosures 의존(V1·V4 이후).

CREATE TABLE notifications (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    disclosure_id   BIGINT      NOT NULL REFERENCES disclosures (id) ON DELETE CASCADE,
    channel         VARCHAR(10) NOT NULL CHECK (channel IN ('KAKAO','TELEGRAM','EMAIL')),
    status          VARCHAR(10) NOT NULL DEFAULT 'PENDING'
                                CHECK (status IN ('PENDING','SENT','FAILED','RETRYING')),
    retry_count     INTEGER     NOT NULL DEFAULT 0,
    sent_at         TIMESTAMPTZ,
    error_message   VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notification_dedup UNIQUE (user_id, disclosure_id, channel)
);

CREATE INDEX idx_notifications_user   ON notifications (user_id, created_at DESC);
CREATE INDEX idx_notifications_status ON notifications (status) WHERE status IN ('PENDING','RETRYING');
