-- V8__create_consent_logs.sql
-- [목적] 동의 이력을 정책 버전별로 누적 보존하는 INSERT-only 테이블 (통합기획서 §11.1 리스크1·리스크3).
-- [이유] users.*_agreed_at는 시각 단일 컬럼이라 정책 재동의 시 이전 이력이 덮어써져 법적 증명이 불가.
-- [사이드 임팩트] 회원가입·재동의 흐름에서 INSERT 추가. users.*_agreed_at은 "최초 동의 시각"으로 의미 재정의.
-- [수정 시 고려사항] UPDATE/DELETE 금지(불변 증거). 최신 동의 상태는 (user_id, consent_type) MAX(agreed_at) 행.
--                  policy_version은 시맨틱 'v{major}.{minor}' 고정(CHECK 정규식). 약관 본문은 legal/{type}_v{X.Y}.md로 보존.

CREATE TABLE consent_logs (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    consent_type    VARCHAR(15)  NOT NULL
                                 CHECK (consent_type IN ('TERMS','PRIVACY','DISCLAIMER','MARKETING')),
    agreed          BOOLEAN      NOT NULL,
    policy_version  VARCHAR(20)  NOT NULL
                                 CHECK (policy_version ~ '^v\d+\.\d+$'),
    agreed_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  consent_logs IS '동의 이력 누적 — INSERT-only. 최신 상태는 (user_id, consent_type) MAX(agreed_at). 법적 증거.';
COMMENT ON COLUMN consent_logs.user_id        IS 'ON DELETE RESTRICT — 사용자 탈퇴 후에도 보존(통합기획서 §11.1)';
COMMENT ON COLUMN consent_logs.policy_version IS '시맨틱 버전 v{major}.{minor}. 약관/개인정보/면책 각각 별도 버전. 본문은 legal/{type}_v{X.Y}.md';

CREATE INDEX idx_consent_logs_user_type
    ON consent_logs (user_id, consent_type, agreed_at DESC);
