-- V9__create_feedbacks.sql
-- [목적] 분석 결과에 대한 사용자 피드백(유용함/부정확함) 누적 (통합기획서 §4.6, §13.3 데이터 해자).
-- [이유] 정확도 KPI(§8.3 알림 정확도 90%) 검증 경로 + 도메인 특화 모델 학습 데이터 원천 확보.
-- [사이드 임팩트] 분석 상세 화면에 피드백 연동 API 필요(후속). INACCURATE 임계치 누적 시 비공개 처리(§11.1 리스크2)는 후속.
-- [수정 시 고려사항] 동일 (user_id, analysis_id) 재투표는 INSERT가 아닌 UPDATE(uq 제약으로 강제). reason은 앱 계층에서 길이 캡 권장.

CREATE TABLE feedbacks (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users (id)            ON DELETE CASCADE,
    analysis_id  BIGINT       NOT NULL REFERENCES analysis_results (id) ON DELETE CASCADE,
    verdict      VARCHAR(15)  NOT NULL CHECK (verdict IN ('USEFUL','INACCURATE')),
    reason       TEXT,                                       -- 부정확 사유(선택)
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_feedbacks_user_analysis UNIQUE (user_id, analysis_id)
);

COMMENT ON TABLE  feedbacks IS '분석 정확도 모니터링·모델 개선의 원천(통합기획서 §4.6, §13.3 데이터 해자)';
COMMENT ON COLUMN feedbacks.verdict IS 'USEFUL/INACCURATE. 동일 user+analysis 재투표는 UPDATE(uq_feedbacks_user_analysis)';

CREATE INDEX idx_feedbacks_analysis_verdict ON feedbacks (analysis_id, verdict);
CREATE INDEX idx_feedbacks_created          ON feedbacks (created_at DESC);
